InpEntryMethod=2
InpTrendTimeframe=16385
InpEntryTimeframe=4
InpFastEMA_Period=7
InpSlow1EMA_Period=30
InpSlow2EMA_Period=60
InpStopLossPoints=300
InpTakeProfit1_Points=300
InpTakeProfit2_Points=700
InpUseTrailingSL=true
InpTrailingStartPoints=350
InpTrailingStopPoints=150
InpRiskPercent=0.3
InpUseDailyFilter=false
InpUseAdxFilter=true
...
