InpFastEMA_Period: start 7 step 1 stop 10
InpSlow1EMA_Period: start 26 step 1 stop 28
InpSlow2EMA_Period: start 45 step 5 stop 60
InpStopLossPoints: start 250 step 0 stop 250
InpTakeProfit1_Points: start 250 step 0 stop 250
InpTakeProfit2_Points: start 500 step 100 stop 900
InpUseTrailingSL: start true step false stop true
InpTrailingStartPoints: start 300 step 50 stop 400
InpTrailingStopPoints: start 100 step 50 stop 200
InpRiskPercent: start 0.4 step 0.1 stop 0.5
InpUseDailyFilter: start true step false stop true
InpUseAdxFilter: start true step false stop true
InpUseDiCrossover: start false step true stop true
InpAdxPeriod: start 31 step 0 stop 31
InpAdxThreshold: start 29 step 0 stop 29
InpUseSessionFilter: start false step false stop false
InpBreakoutLookbackBars: start 12 step 1 stop 17
InpBreakoutOffsetPoints: start 20 step 10 stop 40
InpUseLossLimit: start false step false stop false
InpEntryMethod: start 2 step 0 stop 2
InpTrendTimeframe: start 30 step 0 stop 30
InpEntryTimeframe: start 4 step 0 stop 4